image: alpine:latest

stages:
  - test
  - secret-detection
  - deploy

before_script:
  - apk update
  - apk add python3 py3-pip
  - PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install -r requirements.docs.txt

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

sast:
  stage: test

secret_detection:
  stage: secret-detection

pages:
  stage: deploy
  script:
    - sh ./make-docs.sh
  artifacts:
    paths:
      - site
  publish: site
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
